version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverse-proxy
    image: binwelbeck/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: binwelbeck/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: binwelbeck/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: binwelbeck/udagram-frontend:local
