orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: binwelbeck/reverseproxy
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
            username: $DOCKER_USERNAME 
            password: $DOCKER_PASSWORD

jobs:
    publishLatestToHub: 
      executor: docker-publisher
 
      steps: 
        - checkout
        - setup_remote_docker
        - run:
          name: Install `docker-compose`
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker-compose -f docker-compose-build.yaml build --parallel
              docker push $IMAGE_NAME
workflows:
  version: 2
  build-master:
    jobs:
       - publishLatestToHub
